"use client";

import { useChat } from "ai/react";
import { MessageCircle } from "lucide-react";
import { useEffect, useRef } from "react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

export function ChatWidget() {
  const scrollRef = useRef<HTMLDivElement>(null);
  const { messages, input, handleInputChange, handleSubmit, isLoading } =
    useChat({
      api: "/api/chat",
    });

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    const viewport = el.parentElement;
    if (!viewport) return;
    viewport.scrollTop = viewport.scrollHeight;
  }, [messages]);

  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button
          type="button"
          size="icon"
          className="fixed bottom-6 right-6 z-40 size-12 rounded-full shadow-lg"
          aria-label="Open chat assistant"
        >
          <MessageCircle className="size-6" aria-hidden />
        </Button>
      </SheetTrigger>
      <SheetContent
        side="right"
        className="flex h-full max-h-dvh w-full flex-col sm:max-w-md"
      >
        <SheetHeader>
          <SheetTitle>Ask about this portfolio</SheetTitle>
          <SheetDescription>
            Chat messages are generated by an AI assistant and may be
            inaccurate. Do not share passwords or private data.
          </SheetDescription>
        </SheetHeader>
        <ScrollArea
          className="mt-4 h-[min(420px,calc(100dvh-12rem))] flex-1 pr-3"
          aria-label="Chat transcript"
        >
          <div
            ref={scrollRef}
            role="log"
            aria-live="polite"
            aria-relevant="additions"
            aria-label="Conversation"
            className="flex flex-col gap-3 pb-4"
          >
            {messages.length === 0 && (
              <p className="text-sm text-muted-foreground">
                Ask anything about limitisthesky.dev — work, skills, or
                projects.
              </p>
            )}
            {messages.map((m) => (
              <article
                key={m.id}
                aria-label={m.role === "user" ? "Your message" : "Assistant reply"}
                className={`rounded-lg px-3 py-2 text-sm ${
                  m.role === "user"
                    ? "ml-6 bg-primary text-primary-foreground"
                    : "mr-6 bg-muted text-muted-foreground"
                }`}
              >
                <span className="mb-1 block text-xs font-medium opacity-80">
                  {m.role === "user" ? "You" : "Assistant"}
                </span>
                <div className="whitespace-pre-wrap">{m.content}</div>
              </article>
            ))}
            {isLoading && (
              <p
                role="status"
                aria-live="polite"
                className="text-xs text-muted-foreground"
              >
                Assistant is thinking…
              </p>
            )}
          </div>
        </ScrollArea>
        <form
          onSubmit={handleSubmit}
          className="mt-4 flex gap-2 border-t border-border pt-4"
          aria-busy={isLoading}
        >
          <label htmlFor="portfolio-chat-message" className="sr-only">
            Message for the assistant
          </label>
          <Input
            id="portfolio-chat-message"
            value={input}
            onChange={handleInputChange}
            placeholder="Message…"
            className="flex-1"
            autoComplete="off"
            name="message"
            type="text"
            enterKeyHint="send"
            minLength={1}
            disabled={isLoading}
          />
          <Button type="submit" disabled={isLoading}>
            {isLoading ? "Sending…" : "Send"}
          </Button>
        </form>
      </SheetContent>
    </Sheet>
  );
}
